---
- name: Install influxdb and grafana
  pacman:
    name:
      - grafana
      - influxdb-bin
      # required for ansible
      - python-influxdb
    state: present
  tags: packages
- name: Install telegraf
  become: true
  become_user: aur_builder
  aur:
    name: telegraf
    state: present
  tags: packages
- name: Setup influxdb config
  copy:
    src: files/etc/influxdb/influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    owner: influxdb
    group: influxdb
    mode: u=rw,g=r,o-rwx
    directory_mode: u=rwx,g=rx,o-rwx
  notify: restart influxdb
  tags: configuration
- name: Setup grafana config
  copy:
    src: files/etc/grafana.ini
    dest: /etc/grafana.ini
    owner: grafana
    group: grafana
    mode: u=rw,g=r,o-rwx
    directory_mode: u=rwx,g=rx,o-rwx
  notify: restart grafana
  tags: configuration
- name: Setup grafana datasources and dashboards
  copy:
    src: files/var/lib/grafana/
    dest: /var/lib/grafana/
    owner: grafana
    group: grafana
    mode: u=rw,g=r,o-rwx
    directory_mode: u=rwx,g=rx,o-rwx
  notify: restart grafana
  tags: configuration
- name: Setup telegraf config
  copy:
    src: files/etc/telegraf/
    dest: /etc/telegraf/
    owner: telegraf
    group: telegraf
    mode: u=rw,g=r,o-rwx
    directory_mode: u=rwx,g=rx,o-rwx
  notify: restart telegraf
  tags: configuration
- name: Allow telegraf user to read logs
  user:
    name: telegraf
    groups: log
    append: true
  tags: configuration
- name: Enable services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - grafana
    - influxdb
    - telegraf
  tags: systemctl
- name: Setup web access through nginx reverse proxy
  when: "'webserver' in ansible_role_names"
  copy:
    src: files/etc/nginx/conf.d/10-host.d/
    dest: /etc/nginx/conf.d/10-host.d/
    owner: http
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  notify: reload nginx
  tags: configuration
- name: Setup influxdb databases
  influxdb_database:
    database_name: "{{ item }}"
    state: present
  with_items:
    - telegraf
    - home-assistant
- name: Setup monit config
  when: "'monit' in ansible_role_names"
  copy:
    src: files/etc/monitrc.d/influxdb.conf
    dest: /etc/monitrc.d/influxdb.conf
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  notify: restart monit
  tags: configuration
- name: Allow telegraf to run sudo for certain commands
  copy:
    src: files/etc/sudoers.d/10-telegraf
    dest: /etc/sudoers.d/10-telegraf
    owner: root
    group: root
    mode: u=r,g=r,o-rwx
    validate: "visudo -cf %s"
  tags: configuration
