- name: Install collectd server
  pacman:
    name: collectd
    state: present
  tags: packages
- name: Setup collectd.conf
  copy:
    src: files/etc/collectd.conf
    dest: /etc/collectd.conf
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    validate: 'collectd -t -C %s'
  notify: restart collectd
  tags: configuration
- name: collectd is enabled and running
  systemd:
    name: collectd
    enabled: yes
    state: started
  tags: systemctl
- name: Setup monit config
  copy:
    src: files/etc/monitrc.d/
    dest: /etc/monitrc.d/
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  when: "'server' in ansible_role_names"
  notify: restart monit
  tags: configuration
