---
- name: Install collectd server
  package:
    name: collectd
    state: present
  tags: packages
- name: Setup collectd.conf
  copy:
    src: "files/etc/collectd-{{ ansible_distribution | lower }}.conf"
    dest: "{{ collectd_path }}/etc/collectd.conf"
    owner: "{{ collectd_user }}"
    group: "{{ collectd_group }}"
    mode: u+rw,g-rwx,o-rwx
    validate: "{{ collectd_path }}/sbin/collectd -t -C %s"
  notify:
    - restart collectd on osx
    - restart collectd on archlinux
  tags: configuration
- name: collectd is enabled and running
  systemd:
    name: collectd
    enabled: true
    state: started
  when: ansible_distribution == 'Archlinux'
  tags: systemctl
- name: collectd is enabled and running
  homebrew_services:
    name: collectd
    state: started
  become: true
  when: ansible_distribution == 'MacOSX'
  tags: systemctl
- name: Setup monit config
  copy:
    src: files/etc/monitrc.d/
    dest: /etc/monitrc.d/
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  when: "'monit' in ansible_role_names"
  notify: restart monit
  tags: configuration
