---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
- name: reload fail2ban
  systemd:
    name: fail2ban
    state: reloaded
- name: reload goaccess.service
  systemd:
    daemon_reload: true
- name: restart goaccess
  systemd:
    name: goaccess
    state: restarted
- name: restart oauth2_proxy
  systemd:
    name: oauth2_proxy
    state: restarted
