---
sudo: required
dist: bionic

language: python
python: "3.8"

env:
  - >-
    PIPENV_IGNORE_VIRTUALENVS=1
    PIPENV_VENV_IN_PROJECT=1
    VAGRANT_DEFAULT_PROVIDER=libvirt

cache:
  directories:
    - /home/travis/.vagrant.d/boxes

branches:
  only:
    - master

git:
  # handle submodules ourselves so we use https instead of ssh on Travis
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - sudo apt-get update -qq

install:
  # install libvrt & KVM
  - >-
    sudo apt-get update &&
    sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin
    libvirt-dev qemu-kvm qemu-utils ruby-dev

  # install vagrant
  - >-
    wget -nv
    https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
  - sudo dpkg -i vagrant_2.2.9_x86_64.deb
  - sudo vagrant plugin install vagrant-libvirt

  # install Python 3 for usage together with sudo
  - sudo apt-get install python3.7
  - curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3.7
  - sudo -H pip3 install pipenv

  # install all dependencies
  - sudo -H pipenv install -d

script:
  # install dependencies
  - sudo -H ansible-galaxy install -r requirements.yml

  # run lint against all playbooks
  - sudo -H ansible-lint site.yaml
  - sudo -H ansible-lint macbook.yaml
  - sudo -H ansible-lint grissom.yaml
  - sudo -H ansible-lint openwrt.yaml
  - sudo -H ansible-lint ec2.yaml
  - sudo -H yamllint .

  # run python checks
  - sudo -H pyre

  # test server role
  - cd roles/server/
  - sudo -H molecule test
