---
sudo: required
dist: bionic

language: python
python: "3.6"

branches:
  only:
    - master

git:
  # handle submodules ourselves so we use https instead of ssh on Travis
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - sudo apt-get update -qq

install:
  - >-
    wget -nv
    https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
  - dpkg -i vagrant_2.2.7_x86_64.deb
  - pip install ansible
  - pip install ansible-lint
  - pip install yamllint
  - pip install molecule
  - pip install molecule-vagrant

script:
  # run lint against all playbooks
  - ansible-lint site.yaml
  - ansible-lint macbook.yaml
  - ansible-lint grissom.yaml
  - ansible-lint openwrt.yaml
  - ansible-lint ec2.yaml
  - yamllint .

  # test server role
  - cd roles/server/
  - molecule test
