---
sudo: required
dist: bionic

language: python
python: "3.6"

cache:
  directories:
    - /home/travis/.vagrant.d/boxes

branches:
  only:
    - master

git:
  # handle submodules ourselves so we use https instead of ssh on Travis
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - sudo apt-get update -qq

install:
  - >-
    sudo apt-get update &&
    sudo apt-get -y install libvirt-dev qemu-kvm libvirt-bin
    ubuntu-vm-builder bridge-utils
  - >-
    wget -nv
    https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
  - sudo dpkg -i vagrant_2.2.9_x86_64.deb
  - vagrant plugin install vagrant-libvirt
  - pip install ansible
  - pip install ansible-lint yamllint
  - sudo pip3 install molecule molecule-vagrant

script:
  # run lint against all playbooks
  - ansible-lint site.yaml
  - ansible-lint macbook.yaml
  - ansible-lint grissom.yaml
  - ansible-lint openwrt.yaml
  - ansible-lint ec2.yaml
  - yamllint .

  # test server role
  - cd roles/server/
  - sudo molecule test
