#!/usr/bin/env ansible-playbook
---
- hosts: all
  vars:
    ansible_become_password: "{{ secret_luizribeiro_initial_password }}"
  become: true
  roles:
    - role: base
    - role: server
      vars:
        ssh_require_2fac: false
    - role: luizribeiro
      vars:
        luizribeiro_setup_google_authenticator: false
        luizribeiro_groups:
          - sshusers
          - wheel
    - role: dev
