#!/usr/bin/env ansible-playbook
---
- hosts: "{{ custom_hosts | default('ec2') }}"
  remote_user: "{{ custom_remote_user | default('luiz') }}"
  vars_files:
    - secrets.yaml
  vars:
    ansible_become_password: "{{ secret_luizribeiro_initial_password }}"
  become: true
  roles:
    - role: server
      vars:
        ssh_require_2fac: "{{ custom_ssh_require_2fac | default(true) }}"
      tags: server
    - role: luizribeiro
      vars:
        luizribeiro_setup_google_authenticator: true
      tags: luizribeiro
