- hosts: nuc
  become: yes
  tasks:
    - name: Install fail2ban
      pacman:
        name: fail2ban
        state: latest
        update_cache: yes
      register: upgrade
    - name: Setup fail2ban settings
      copy:
        src: ./etc/fail2ban/jail.local
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: u+rw,g-rwx,o-rwx
      register: config
    - name: Enable fail2ban
      systemd:
        name: fail2ban
        enabled: yes
    - name: Restart fail2ban
      systemd:
        name: fail2ban
        state: restarted
      when: config.changed or upgrade.changed
