#!/usr/bin/env ansible-playbook
---
- hosts: grissom
  vars_files:
    - secrets.yaml
  roles:
    - role: luizribeiro
      vars:
        luizribeiro_primary_group: staff
        luizribeiro_groups:
          - admin
      tags: luizribeiro
    - role: collectd
      tags: collectd
    - role: dev
      vars:
        dev_ansible_tools: true
        dev_aws_tools: true
      tags: dev
    - role: osx
      vars:
        osx_additional_casks:
          - google-chrome
          - mailspring
          - steam
          - stellarium
          - whatsapp
        osx_additional_mas_apps:
          - { id: 1091189122, name: "Bear" }
          - { id: 1153157709, name: "Speedtest" }
          - { id: 1440801586, name: "Cascable Transfer" }
          - { id: 1449412482, name: "Reeder" }
          - { id: 497799835, name: "Xcode" }
          - { id: 568052099, name: "AmpKit" }
          - { id: 1116599239, name: "NordVPN IKE" }
      tags: osx
    - role: backup
      vars:
        backup_user: root
        backup_user_group: wheel
        backup_script_path: /var/root/backup.sh
        backup_paths:
          - /Users
          - /usr/local/etc
        backup_excludes:
          # ncdu -X /var/root/backup-excludes.txt /Users
          - /Users/**/.*
          - /Users/**/Library
          - /Users/Shared/Adobe
          - /Users/Shared/Epic Games
          - /Users/Shared/GOG.com
          - /Users/luiz/Music
          # these are backed up to Dropbox
          - /Users/**/Dropbox
          # these are backed up to Adobe Creative Cloud
          - /Users/**/Creative Cloud Files
          - /Users/luiz/Pictures/Lightroom Library.lrlibrary
          # these are backed up to iCloud
          - /Users/luiz/Pictures/Photos Library.photoslibrary
          # I need to figure out if I have to back these up
          - /Users/luiz/Pictures/nobackup
