#!/usr/bin/env ansible-playbook
---
- hosts: husky
  vars:
    ansible_become_password: "{{ secret_luizribeiro_initial_password }}"
  become: true
  roles:
    - role: server
      vars:
        ssh_require_2fac: false
    - role: luizribeiro
      vars:
        luizribeiro_groups:
          - dialout
          - sshusers
          - wheel
    - role: dev
      vars:
        dev_cpp_tools: true
        dev_python_tools: true
