#!/usr/bin/env ansible-playbook
---
- hosts: iot-mariner
  vars:
    ansible_become_password: "{{ secret_luizribeiro_initial_password }}"
  become: true
  roles:
    - role: luizribeiro
      vars:
        luizribeiro_groups:
          - dialout
          - sshusers
          - wheel
  post_tasks:
    - name: Enable USB driver for gadget modes
      lineinfile:
        path: /boot/config.txt
        line: "dtoverlay=dwc2"
    - name: Enable dwc2 kernel module
      lineinfile:
        path: /boot/cmdline.txt
        backrefs: true
        regexp: '(^.+rootwait(\s+(?!modules-load=dwc2)[\w=/\-\.]+)*)\s*$'
        line: '\1 modules-load=dwc2'
        state: present
    - name: Setup container file
      command: dd bs=1M if=/dev/zero of=/piusb.bin count=2048
      args:
        creates: /piusb.bin
      notify: Setup partition on container file
    - name: Create mount point for container file
      file:
        name: /mnt/usb_share
        state: directory
    - name: Mount container file
      lineinfile:
        path: /etc/fstab
        line: "/piusb.bin /mnt/usb_share vfat users,umask=000 0 2"
      notify: Reload fstab
    - name: Create sync directory within /mnt/usb_share
      file:
        name: /mnt/usb_share/sync
        state: directory
    - name: Setup /etc/rc.local
      template:
        src: files/iot-mariner-rc.local
        dest: /etc/rc.local
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
    - name: Create lsync user account
      user:
        name: lsync
        groups: sshusers
        append: true
        expires: -1
      tags: configuration
    - name: Enable UART
      lineinfile:
        path: /boot/config.txt
        line: "enable_uart=1"
    - name: Disable service for console over serial port
      systemd:
        name: "serial-getty@ttyS0"
        state: stopped
        enabled: false
    - name: Remove console from cmdline.txt
      replace:
        path: /boot/cmdline.txt
        regexp: 'console=serial0,115200\s+'
        replace: ""
    - name: Install python3-pip
      package:
        name: python3-pip
        state: present
    - name: Install python3-venv
      package:
        name: python3-venv
        state: present
    - name: Install poetry
      pip:
        name: poetry
        executable: pip3
    - name: Install dh-virtualenv
      package:
        name: dh-virtualenv
        state: present

  handlers:
    - name: Setup partition on container file
      command: mkdosfs /piusb.bin -F 32 -I
    - name: Reload fstab
      command: mount -a
      args:
        warn: false
