#!/usr/bin/env ansible-playbook
---
- hosts: iot-mariner
  become: true
  pre_tasks:
    - name: Enable USB driver for gadget modes
      lineinfile:
        path: /boot/config.txt
        line: "dtoverlay=dwc2"
  roles:
    - role: luizribeiro
