#!/usr/bin/env ansible-playbook
---
- hosts: labmate
  vars:
    ansible_become_password: "{{ secret_luizribeiro_initial_password }}"
  become: true
  roles:
    - role: luizribeiro
  tasks:
    # this is required for numpy
    - name: Install libatlas-base-dev
      package:
        name: libatlas-base-dev
        state: present
    - name: Install python3-pip
      package:
        name: python3-pip
        state: present
    - name: Install python3-venv
      package:
        name: python3-venv
        state: present
    - name: Install python3-wheel
      package:
        name: python3-wheel
        state: present
    - name: Install poetry
      pip:
        name: poetry
        executable: pip3
