#!/usr/bin/env ansible-playbook
---
- hosts: labmate
  vars:
    ansible_become_password: "{{ secret_luizribeiro_initial_password }}"
  become: true
  roles:
    - role: luizribeiro
  tasks:
    - name: Install python3-pip
      package:
        name: python3-pip
        state: present
    - name: Install poetry
      pip:
        name: poetry
        executable: pip3
