#!/usr/bin/env ansible-playbook --ask-become-pass
---
- hosts: macbook
  pre_tasks:
    - name: Check we are running on the right host
      assert:
        that:
          - ansible_distribution == 'MacOSX'
          - ansible_user_id == 'luizribeiro'
          - ansible_model is match("MacBook.*")
        quiet: true
    - name: Refresh sudo cache
      command: "echo none"
      become: true
      check_mode: false
      changed_when: false
  roles:
    - role: luizribeiro
      vars:
        luizribeiro_username: luizribeiro
        luizribeiro_primary_group: "{{ omit }}"
        luizribeiro_groups:
          - admin
      tags: luizribeiro
    - role: dev
      vars:
        dev_qmk_firmware_tools: true
      tags: dev
    - role: osx
      vars:
        osx_additional_casks:
          - charles
          - gswitch
          - quip
          - slack
        osx_additional_mas_apps:
          - { id: 414030210, name: "LimeChat" }
          - { id: 937984704, name: "Amphetamine" }
      tags: osx
