#!/usr/bin/env ansible-playbook
---
- hosts: nuc.thepromisedlan.club
  vars:
    letsencrypt_email: "luizribeiro@gmail.com"
  vars_files:
    - secrets.yaml
  become: true
  pre_tasks:
    - name: Setup /etc/hosts
      template:
        src: files/nuc-hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      tags: configuration
    - name: "Timezone is America/New_York"
      file:
        state: link
        src: "/usr/share/zoneinfo/America/New_York"
        dest: /etc/localtime
      notify: regenerate /etc/adjtime
      tags: configuration
    - name: "Hostname is nuc"
      copy:
        content: "nuc\n"
        dest: /etc/hostname
  roles:
    - role: server
      tags: server
    - role: collectd
      tags: collectd
    - role: luizribeiro
      tags: luizribeiro
    - role: dev
      vars:
        dev_ansible_tools: true
      tags: dev
    - role: backup
      vars:
        backup_paths:
          - /etc
          - /home
          - /var/lib/grafana
          - /var/lib/hass
          - /var/lib/influxdb
        backup_excludes:
          - /home/aur_builder
          - /var/lib/hass/home-assistant_v2.db
      tags: backup
    - role: pihole
      tags: pihole
    - role: samba
      tags: samba
    - role: mqtt-broker
      tags: mqtt-broker
    - role: webserver
      tags: webserver
    - role: influxdb
      tags: influxdb
    - role: home-assistant
      tags: home-assistant
  tasks:
    - name: Setup NUC check-vitals.sh script
      copy:
        src: files/check-vitals.sh
        dest: /usr/sbin/check-vitals.sh
        owner: root
        group: root
        mode: u+rwx,g-rwx,o-rwx
      tags: scripts
    - name: Setup NUC custom monit checks
      copy:
        src: files/etc/monitrc.d/nuc.conf
        dest: /etc/monitrc.d/nuc.conf
        owner: root
        group: root
        mode: u+rw,g-rwx,o-rwx
      notify: restart monit
      tags: configuration
    - name: Reboot machine
      reboot:
      tags: [never, reboot]
