#!/usr/bin/env ansible-playbook
---
- hosts: nuc
  vars:
    letsencrypt_email: "luizribeiro@gmail.com"
  vars_files:
    - secrets.yaml
  become: yes
  pre_tasks:
  - name: Setup /etc/hosts
    template:
      src: files/nuc-hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    tags: configuration
  roles:
    - role: server
      tags: server
    - role: luizribeiro
      tags: luizribeiro
    - role: dev
      vars:
        dev_ansible_tools: yes
      tags: dev
    - role: backup
      vars:
        backup_paths:
          - /etc
          - /home
          - /var/lib/hass
      tags: backup
    - role: pihole
      tags: pihole
    - role: samba
      tags: samba
    - role: mqtt-broker
      tags: mqtt-broker
    - role: webserver
      tags: webserver
    - role: home-assistant
      tags: home-assistant
  tasks:
    - name: Upgrade all packages
      block:
        - name: Upgrade pacman packages
          pacman:
            update_cache: yes
            upgrade: yes
        - name: Upgrade AUR packages
          aur:
            upgrade: yes
            aur_only: yes
      tags: [ never, upgrade ]
    - name: Reboot machine
      reboot:
      tags: [ never, reboot ]
