- hosts: nuc
  vars:
    letsencrypt_email: "luizribeiro@gmail.com"
  vars_files:
    - secrets.yaml
  become: yes
  roles:
    - role: common
      tags: common
    - role: luizribeiro
      tags: luizribeiro
    - role: dev
      vars:
        dev_ansible_tools: yes
      tags: dev
    - role: pihole
      tags: pihole
    - role: samba
      tags: samba
    - role: mqtt-broker
      tags: mqtt-broker
    - role: webserver
      tags: webserver
    - role: home-assistant
      tags: home-assistant
  tasks:
    - name: Upgrade all packages
      aur:
        upgrade: yes
      tags: [ never, upgrade ]
