#!/usr/bin/env ansible-playbook
---
- hosts: nuc.thepromisedlan.club
  vars:
    letsencrypt_email: "luizribeiro@gmail.com"
    ansible_become_password: "{{ secret_luizribeiro_initial_password }}"
  become: true
  pre_tasks:
    - name: Setup /etc/hosts
      template:
        src: files/nuc-hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      tags: configuration
    - name: "Timezone is America/Chicago"
      file:
        state: link
        src: "/usr/share/zoneinfo/America/Chicago"
        dest: /etc/localtime
      notify: regenerate /etc/adjtime
      tags: configuration
    - name: "Hostname is nuc"
      copy:
        content: "nuc\n"
        dest: /etc/hostname
  roles:
    - role: server
      vars:
        ssh_require_2fac: true
      tags: server
    - role: collectd
      tags: collectd
    - role: luizribeiro
      vars:
        luizribeiro_setup_google_authenticator: true
      tags: luizribeiro
    - role: backup
      vars:
        backup_paths:
          - /etc
          - /home
          - /var/lib/grafana
          - /var/lib/hass
          - /var/lib/influxdb
        backup_excludes:
          - /home/aur_builder
          - /var/lib/hass/home-assistant_v2.db
      tags: backup
    - role: pihole
      tags: pihole
    - role: samba
      tags: samba
    - role: mqtt-broker
      tags: mqtt-broker
    - role: webserver
      tags: webserver
    - role: influxdb
      tags: influxdb
    - role: home-assistant
      tags: home-assistant
  tasks:
    - name: Setup NUC check-vitals.sh script
      copy:
        src: files/check-vitals.sh
        dest: /usr/sbin/check-vitals.sh
        owner: root
        group: root
        mode: u+rwx,g-rwx,o-rwx
      tags: scripts
    - name: Setup NUC custom monit checks
      copy:
        src: files/etc/monitrc.d/nuc.conf
        dest: /etc/monitrc.d/nuc.conf
        owner: root
        group: root
        mode: u+rw,g-rwx,o-rwx
      notify: restart monit
      tags: configuration
    - name: Install lsyncd
      aur:
        name: lsyncd
        state: present
      tags: packages
    - name: Setup SSH keypair for lsyncd
      openssh_keypair:
        path: /etc/lsyncd/id_rsa
        mode: u=rw,g-rwx,o-rwx
        owner: root
        group: root
      register: lsyncd_ssh_key
      notify: Update lsyncd public SSH key
      tags: configuration
    - name: Setup lsyncd configuration
      copy:
        src: files/nuc-lsyncd.conf.lua
        dest: /etc/lsyncd/lsyncd.conf.lua
        mode: u=rw,g-rwx,o-rwx
        owner: root
        group: root
        directory_mode: u=rwx,g-rwx,o-rwx
      notify: Restart lsyncd
      tags: configuration
    - name: lsyncd is enabled and running
      systemd:
        name: lsyncd
        enabled: true
        state: started
      tags: systemctl
    - name: Reboot machine
      reboot:
      tags: [never, reboot]

  handlers:
    - name: Update lsyncd public SSH key
      delegate_to: iot-mariner
      become: true
      authorized_key:
        user: lsync
        state: present
        key: "{{ lsyncd_ssh_key.public_key }}"
    - name: Restart lsyncd
      systemd:
        name: lsyncd
        state: restarted
