- hosts: nuc
  vars:
    letsencrypt_email: "luizribeiro@gmail.com"
  vars_files:
    - secrets.yaml
  become: yes
  roles:
    - role: common
    - role: dev
      vars:
        dev_ansible_tools: yes
    - role: pihole
    - role: samba
    - role: mqtt-broker
    - role: webserver
    - role: home-assistant
