#!/usr/bin/env ansible-playbook
---
- hosts: openwrt
  roles:
    - role: openwrt
    - role: backup
      vars:
        backup_paths:
          - /
        backup_excludes:
          - /proc
          - /sys
          - /tmp
          - /var
