[tool.poetry]
name = "ansible-boxes"
version = "0.0.1"
description = "My computer provisioning setup with ansible"
authors = [
  "Luiz Ribeiro <luizribeiro@gmail.com>",
]

[tool.poetry.dependencies]
python = "^3.8"
ansible = "2.10.5"
passlib = "1.7.4"

[tool.poetry.dev-dependencies]
ansible-lint = "4.3.7"
molecule = "3.2.2"
molecule-vagrant = "0.6.1"
python-vagrant = "0.5.15"
pyexpect = "1.0.21"
pyre-check = "0.0.58"
pytest = "6.2.1"
python-language-server = "0.36.2"
testinfra = "6.0.0"
yamllint = "1.25.0"

[build-system]
requires = ["poetry>=1.0.10"]
build-backend = "poetry.masonry.api"
