[tool.poetry]
name = "ansible-boxes"
version = "0.0.1"
description = "My computer provisioning setup with ansible"
authors = [
  "Luiz Ribeiro <luizribeiro@gmail.com>",
]

[tool.poetry.dependencies]
python = "^3.8"
ansible = "2.10.1"
passlib = "1.7.4"

[tool.poetry.dev-dependencies]
ansible-lint = "4.3.6"
molecule = "3.0.8"
molecule-vagrant = "0.3"
pyexpect = "1.0.20"
pyre-check = "0.0.57"
pytest = "6.1.1"
python-language-server = "0.35.1"
testinfra = "5.3.1"
yamllint = "1.25.0"

[build-system]
requires = ["poetry>=1.0.10"]
build-backend = "poetry.masonry.api"
