---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: luizribeiro/arch-base
    memory: 1024
    cpus: 2
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        is_test_environment: true
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    # show which tests where executed in test output
    v: 1
