---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: archlinux/archlinux
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    # show which tests where executed in test output
    v: 1
