---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: "Upgrade system"
      pacman:
        update_cache: true
        upgrade: true
    - name: Disable systemd-resolved
      systemd:
        name: systemd-resolved
        enabled: false
        state: stopped
    - name: Setup /etc/resolv.conf
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4
    - name: "Reboot machine after upgrade"
      reboot:
