---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: "Upgrade system"
      pacman:
        update_cache: true
        upgrade: true
    - name: Disable systemd-resolved
      systemd:
        name: systemd-resolved
        enabled: false
        state: stopped
    - name: "Reboot machine after upgrade"
      reboot:
