- name: restart sshd
  systemd:
    name: sshd
    state: restarted
- name: restart collectd
  systemd:
    name: collectd
    state: restarted
- name: restart monit
  systemd:
    name: monit
    state: restarted

- name: regenerate /etc/adjtime
  command: hwclock --systohc
