---
- name: Install Samba server
  pacman:
    name: samba
    state: present
  tags: packages
- name: Setup smb.conf
  template:
    src: files/etc/samba/smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    validate: "testparm -s %s"
  notify:
    - restart smbd
    - restart nmbd
  tags: configuration
- name: Create /home/public directory
  file:
    path: /home/public
    state: directory
    owner: nobody
    group: nobody
    mode: u=rwx,g=rx,o=rx
  tags: configuration
- name: smbd is enabled and running
  systemd:
    name: smb
    enabled: yes
    state: started
  tags: systemctl
- name: nmbd is enabled and running
  systemd:
    name: nmb
    enabled: yes
    state: started
  tags: systemctl
- name: Setup monit config
  copy:
    src: files/etc/monitrc.d/
    dest: /etc/monitrc.d/
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  notify: restart monit
  tags: configuration
