- name: Install Samba server
  pacman:
    name: samba
    state: present
  notify: restart samba
- name: Setup smb.conf
  template:
    src: files/etc/samba/smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    validate: "testparm -s %s"
  notify: restart samba
- name: Create /home/public directory
  file:
    path: /home/public
    state: directory
    owner: nobody
    group: nobody
    mode: u=rwx,g=rx,o=rx
- name: smbd is enabled and running
  systemd:
    name: smb
    enabled: yes
    state: started
- name: nmbd is enabled and running
  systemd:
    name: nmb
    enabled: yes
    state: started
