---
- name: Install bluetooth packages
  pacman:
    name:
      - bluez
      - bluez-utils
    state: present
  tags: packages
- name: bluetooth.service is enabled and running
  systemd:
    name: bluetooth
    enabled: true
    state: started
  tags: systemctl
- name: Setup monit config
  copy:
    src: files/etc/monitrc.d/
    dest: /etc/monitrc.d/
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  notify: restart monit
  tags: configuration
