- name: Install bluetooth packages
  pacman:
    name:
      - bluez
      - bluez-utils
    state: present
- name: bluetooth.service is enabled and running
  systemd:
    name: bluetooth
    enabled: yes
    state: started
