- name: Install home-assistant
  pacman:
    state: present
    name:
      - home-assistant
      # this should be a dependency of home-assistant. see FS#64963
      - python-aiohttp-cors
      - python-bluepy
- name: Setup home-assistant
  copy:
    src: files/var/lib/hass/
    dest: /var/lib/hass/
    owner: hass
    group: hass
    mode: u=rw,g=r,o-rwx
    directory_mode: u=rwx,g=rx,o-rwx
    validate: 'hass -c %s --script check_config'
  notify: restart home-assistant
- name: Setup nginx for home-assistant
  copy:
    src: files/etc/nginx/conf.d/10-home.conf
    dest: /etc/nginx/conf.d/10-home.conf
    owner: http
    mode: u+rw,g-rwx,o-rwx
    # TODO: figure out a way of validating nginx/conf.d/10-home.conf
  notify: restart nginx
- name: Setup home-assistant.service overrides
  copy:
    src: files/etc/systemd/system/home-assistant.service.d/
    dest: /etc/systemd/system/home-assistant.service.d/
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx
  notify:
    - reload home-assistant.service
    - restart home-assistant
- name: home-assistant is enabled and running
  systemd:
    name: home-assistant
    enabled: yes
    state: started
