- name: Install home-assistant
  pacman:
    name:
      - home-assistant
      # this should be a dependency of home-assistant. see FS#64963
      - python-aiohttp-cors
      - python-bluepy
    state: latest
    update_cache: yes
  register: hass_upgrade
- name: Setup home-assistant
  copy:
    src: ../files/var/lib/hass/
    dest: /var/lib/hass/
    owner: hass
    group: hass
    mode: u=rw,g=r,o-rwx
    directory_mode: u=rwx,g=rx,o-rwx
  register: hass_config
- name: Setup nginx for home-assistant
  copy:
    src: ../files/etc/nginx/conf.d/10-home.conf
    dest: /etc/nginx/conf.d/10-home.conf
    owner: http
    mode: u+rw,g-rwx,o-rwx
  register: nginx_confd
- name: Setup home-assistant.service overrides
  copy:
    src: ../files/etc/systemd/system/home-assistant.service.d/
    dest: /etc/systemd/system/home-assistant.service.d/
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx
  register: home_assistant_service
- name: Reload home-assistant.service
  systemd:
    daemon_reload: yes
  when: home_assistant_service.changed
- name: Enable home-assistant
  systemd:
    name: home-assistant
    enabled: yes
- name: Check and restart home-assistant
  block:
    - name: Check home-assistant config
      command: hass -c /var/lib/hass/ --script check_config
    - name: Restart home-assistant
      systemd:
        name: home-assistant
        state: restarted
  when: hass_upgrade.changed or home_assistant_service.changed or hass_config.changed
