- name: Install home-assistant
  pacman:
    name:
      - home-assistant
      # this should be a dependency of home-assistant. see FS#64963
      - python-aiohttp-cors
      # TODO: setup bluetooth
    state: latest
    update_cache: yes
  register: hass_upgrade
- name: Setup home-assistant
  copy:
    src: ../files/var/lib/hass/
    dest: /var/lib/hass/
    owner: hass
    group: hass
    mode: u=rw,g=r,o-rwx
    directory_mode: u=rwx,g=rx,o-rwx
  register: hass_config
- name: Setup nginx for home-assistant
  copy:
    src: ../files/etc/nginx/conf.d/10-home.conf
    dest: /etc/nginx/conf.d/10-home.conf
    owner: http
    mode: u+rw,g-rwx,o-rwx
  register: nginx_confd
- name: Enable home-assistant
  systemd:
    name: home-assistant
    enabled: yes
    # TODO: customize home-assistant.service so it sets up a pid file
- name: Check and restart home-assistant
  block:
    - name: Check home-assistant config
      command: hass -c /var/lib/hass/ --script check_config
    - name: Restart home-assistant
      systemd:
        name: home-assistant
        state: restarted
  when: hass_upgrade.changed or hass_config.changed
