---
- name: Install home-assistant
  pacman:
    state: present
    name:
      - home-assistant
      - python-bluepy
  tags: packages
- name: Setup secrets.yaml for home-assistant
  copy:
    content: "{{ secret_home_assistant_secrets_yaml }}"
    dest: /var/lib/hass/secrets.yaml
    owner: hass
    group: hass
    mode: u=rw,g-rwx,o-rwx
  notify: restart home-assistant
  tags: configuration
- name: Setup webostv.conf for home-assistant
  copy:
    content: "{{ secret_home_assistant_webostv_conf }}"
    dest: /var/lib/hass/webostv.conf
    owner: hass
    group: hass
    mode: u=rw,g-rwx,o-rwx
  notify: restart home-assistant
  tags: configuration
- name: Setup service-account.json for home-assistant
  copy:
    content: "{{ secret_home_assistant_service_account_json }}"
    dest: /var/lib/hass/service-account.json
    owner: hass
    group: hass
    mode: u=rw,g-rwx,o-rwx
  notify: restart home-assistant
  tags: configuration
- name: Setup home-assistant configuration
  copy:
    src: files/var/lib/hass/
    dest: /var/lib/hass/
    owner: hass
    group: hass
    mode: u=rw,g=r,o-rwx
    directory_mode: u=rwx,g=rx,o-rwx
    # TODO: fix hass-config validation
    #validate: 'hass -c %s --script check_config'
  notify: restart home-assistant
  tags: configuration
- name: Setup nginx for home-assistant
  copy:
    src: files/etc/nginx/conf.d/
    dest: /etc/nginx/conf.d/
    owner: http
    mode: u+rw,g-rwx,o-rwx
    # TODO: figure out a way of validating nginx/conf.d/20-home.conf
  notify: reload nginx
  tags: configuration
- name: Setup SSL certificate
  command: "certbot certonly -n --nginx -m '{{ letsencrypt_email | mandatory }}' --agree-tos -d home.thepromisedlan.club"
  args:
    creates: /etc/letsencrypt/live/home.thepromisedlan.club/
  notify: reload nginx
  tags: configuration
- name: Setup home-assistant.service overrides
  copy:
    src: files/etc/systemd/system/home-assistant.service.d/
    dest: /etc/systemd/system/home-assistant.service.d/
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx
  notify:
    - reload home-assistant.service
    - restart home-assistant
  tags: configuration
- name: home-assistant is enabled and running
  systemd:
    name: home-assistant
    enabled: yes
    state: started
  tags: systemctl
- name: Setup monit config
  copy:
    src: files/etc/monitrc.d/
    dest: /etc/monitrc.d/
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  notify: restart monit
  tags: configuration
- name: Allow users in log group to read Home Assistant logs
  file:
    path: /var/lib/hass/home-assistant.log
    owner: hass
    group: log
    mode: u=rw,g=r,o-rwx
  tags: configuration
