---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Include server"
      include_role:
        name: "server"
    - name: "Add vagrant user to sshusers"
      user:
        name: vagrant
        groups: sshusers
        append: true
    - name: "Disable ssh rate limiting for VM host"
      ufw:
        rule: allow
        insert: 1
        src: 192.168.121.1
        port: 22
