---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  # FIXME: for some reason debian is failing to reboot during prepare playbook
  # - name: debian
  #   box: debian/buster64
  - name: archlinux
    box: archlinux/archlinux
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        is_test_environment: true
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    # show which tests where executed in test output
    v: 1
