---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: debian
    box: generic/debian10
  - name: archlinux
    box: archlinux/archlinux
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        is_test_environment: true
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    # show which tests where executed in test output
    v: 1
