---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: "Upgrade pacman packages"
      pacman:
        update_cache: true
        upgrade: true
      when: ansible_distribution == 'Archlinux'
    - name: "Setup grub device path"
      # this is required so grub-pc upgrades work on the VM, since during
      # upgrade it prompts for a path to install grub on
      debconf:
        name: grub-pc
        question: grub-pc/install_devices
        value: /dev/sda
        vtype: string
      when: ansible_distribution == 'Debian'
    - name: "Upgrade apt packages"
      apt:
        update_cache: true
        upgrade: full
      when: ansible_distribution == 'Debian'
    - name: "Reboot machine after upgrade"
      reboot:
