---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: "Upgrade pacman packages"
      pacman:
        update_cache: true
        upgrade: true
    - name: "Reboot machine after upgrade"
      reboot:
