- name: Install backup software
  package:
    name:
      - restic
      - rclone
    state: present
  tags: packages
- name: Make sure config directory exists
  file:
    path: "{{ rclone_conf_path | dirname }}"
    owner: "{{ backup_user }}"
    group: "{{ backup_user_group }}"
    state: directory
    mode: u+rwx,g-rwx,o-rwx
    recurse: yes
  become: yes
  tags: configuration
- name: Setup rclone
  template:
    src: templates/rclone.conf
    dest: "{{ rclone_conf_path }}"
    owner: "{{ backup_user }}"
    group: "{{ backup_user_group }}"
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  become: yes
  tags: configuration
- name: Setup excludes file
  lineinfile:
    path: "{{ backup_script_path | dirname }}/backup-excludes.txt"
    line: "{{ item }}"
    create: yes
  become: yes
  with_items: "{{ backup_excludes }}"
- name: Initialize backup repository
  command: restic init
  become: yes
  environment:
    RESTIC_REPOSITORY: '{{ restic_backup_repo }}'
    RESTIC_PASSWORD: '{{ secret_restic_password }}'
  no_log: false
  register: restic_init
  changed_when: "'created restic repository' in restic_init.stdout"
  failed_when:
    - restic_init.rc != 0
    - not 'already initialized' in restic_init.stderr
  tags: configuration
- name: Setup backup script
  template:
    src: templates/backup.sh
    dest: "{{ backup_script_path }}"
    owner: "{{ backup_user }}"
    group: "{{ backup_user_group }}"
    mode: u+rwx,g-rwx,o-rwx
  become: yes
  tags: configuration
- include: "schedule-{{ ansible_distribution | lower }}.yaml"
- block:
  - name: Setup backup-check script
    template:
      src: templates/backup-check.sh
      dest: "{{ backup_script_path | dirname }}/backup-check.sh"
      owner: "{{ backup_user }}"
      group: "{{ backup_user_group }}"
      mode: u+rwx,g-rwx,o-rwx
    become: yes
  - name: Setup monit config
    copy:
      src: files/etc/monitrc.d/
      dest: /etc/monitrc.d/
      owner: "{{ backup_user }}"
      group: "{{ backup_user_group }}"
      mode: u+rw,g-rwx,o-rwx
      directory_mode: u+rwx,g-rwx,o-rwx
    notify: restart monit
  when: "'server' in ansible_role_names"
  tags: configuration
