- name: Install backup software
  pacman:
    name:
      - restic
      - rclone
    state: present
  tags: packages
- name: Setup rclone
  template:
    src: templates/rclone.conf
    dest: /root/.config/rclone/rclone.conf
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  tags: configuration
- name: Initialize backup repository
  command: restic init
  environment:
    RESTIC_REPOSITORY: '{{ restic_backup_repo }}'
    RESTIC_PASSWORD: '{{ secret_restic_password }}'
  no_log: false
  register: restic_init
  changed_when: "'created restic repository' in restic_init.stdout"
  failed_when:
    - restic_init.rc != 0
    - not 'already initialized' in restic_init.stderr
  tags: configuration
- name: Setup backup script
  template:
    src: templates/backup.sh
    dest: /root/backup.sh
    owner: root
    group: root
    mode: u+rwx,g-rwx,o-rwx
  tags: configuration
- name: Setup backups as a daily cron job
  cron:
    name: Backup
    minute: "0"
    hour: "4"
    user: root
    job: /root/backup.sh
    cron_file: backups
  tags: configuration
- name: Setup monit config
  copy:
    src: files/etc/monitrc.d/
    dest: /etc/monitrc.d/
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  notify: restart monit
  tags: configuration
