---
- name: Setup local.backup LaunchAgent
  copy:
    src: files/local.backup.plist
    dest: /Library/LaunchAgents/local.backup.plist
    owner: "{{ backup_user }}"
    group: "{{ backup_user_group }}"
    mode: u+rw,g-rwx,o-rwx
  become: yes
  tags: configuration
- name: local.backup Launch Agent is loaded
  launchd:
    name: local.backup
    state: reloaded
  become: yes
  tags: configuration
