---
- name: Setup local.backup LaunchDaemon
  template:
    src: templates/local.backup.plist.jinja
    dest: /Library/LaunchDaemons/local.backup.plist
    owner: "{{ backup_user }}"
    group: "{{ backup_user_group }}"
    mode: u+rw,g-rwx,o-rwx
  become: true
  tags: configuration
- name: local.backup Launch Daemon is loaded
  community.general.launchd:
    name: local.backup
    state: reloaded
  become: true
  tags: configuration
