- name: Setup local.backup LaunchAgent
  copy:
    src: files/local.backup.plist
    dest: /Library/LaunchAgents/local.backup.plist
    owner: "{{ backup_user }}"
    group: "{{ backup_user_group }}"
    mode: u+rw,g-rwx,o-rwx
  become: yes
  tags: configuration
- name: Load and enable local.backup LaunchAgent
  command: launchctl load -w /Library/LaunchAgents/local.backup.plist
  become: yes
