# vim: set ft=yaml.ansible:
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_region: us-east-2
  environment:
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_KEY: "{{ aws_secret_key }}"
  tasks:
    - name: Create ec2 instances
      ec2:
        # from https://www.uplinklabs.net/projects/arch-linux-on-ec2/
        # ebs hvm x86_64 stable us-east-2
        image: ami-0732f750b255470d2
        instance_type: "{{ instance_type | default('t3.micro') }}"
        region: "{{ aws_region }}"
        key_name: GPG
        count: "{{ count | default(1) }}"
        state: present
        wait: true
      register: ec2
    - name: Add instances to hosts file
      lineinfile:
        path: ../../hosts
        regexp: "{{ item.public_dns_name }}"
        line: "{{ item.public_dns_name }}"
        insertafter: "\\[ec2\\]"
      with_items: "{{ ec2.instances }}"
    - name: Create .launched_hosts file
      copy:
        dest: ../../.launched_hosts
        content: "[launched]\n"
    - name: Add instances to .launched_hosts file
      lineinfile:
        path: ../../.launched_hosts
        regexp: "{{ item.public_dns_name }}"
        line: "{{ item.public_dns_name }}"
        insertafter: "\\[launched\\]"
      with_items: "{{ ec2.instances }}"
    - name: Add new instances to launched in-memory launched hosts group
      add_host:
        hostname: "{{ item.public_dns_name }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"
    - name: Restart machines
      ec2:
        instance_ids: "{{ ec2.instance_ids }}"
        region: "{{ aws_region }}"
        state: restarted
        wait: true
    - name: Setup SSH host fingerprints
      block:
        - name: Get host fingerprints
          command: ../fetch-ec2-host-key {{ item.id }}
          changed_when: true
          delegate_to: localhost
          register: host_key
        - name: Add host fingerprint to known hosts
          known_hosts:
            key: "{{ item.public_dns_name }} {{ host_key.stdout }}"
            name: "{{ item.public_dns_name }}"
            state: present
          delegate_to: localhost
      with_items: "{{ ec2.instances }}"

- hosts: launched
  gather_facts: false
  remote_user: arch
  tasks:
    - name: Wait for host to become reachable
      wait_for_connection:

- hosts: launched
  remote_user: arch
  become: true
  tasks:
    - name: Upgrade system
      pacman:
        update_cache: true
        upgrade: true
    - name: Reboot machine
      reboot:
    - name: Wait for host to become reachable again
      wait_for_connection:
    - name: Remove locale.gen from the EC2 AMI
      file:
        path: /etc/locale.gen
        state: absent
    - name: Reinstall glibc so locale.gen contents are from Arch Linux
      command: pacman -S --noconfirm glibc
      args:
        creates: /etc/locale.gen

- import_playbook: ../../ec2.yaml
  vars:
    custom_hosts: launched
    custom_remote_user: arch
    custom_ssh_require_2fac: true
