---
- name: Get host fingerprints
  command: ../ec2-fetch-host-key {{ item.id }}
  changed_when: true
  delegate_to: localhost
  register: host_key
- name: Add host fingerprint to known hosts
  known_hosts:
    key: "{{ item.public_dns_name }} {{ host_key.stdout }}"
    name: "{{ item.public_dns_name }}"
    state: present
  delegate_to: localhost
