---
- name: clone dotfiles repo
  git:
    repo: "https://github.com/luizribeiro/dotfiles"
    dest: "~/.dotfiles"
    version: "HEAD"
  notify:
    - setup dotfiles github remote
    - install dotfiles
  become: true
  become_user: "{{ luizribeiro_username }}"
- name: setup dotfiles github remote
  git_config:
    name: "remote.origin.url"
    value: "git@github.com:luizribeiro/dotfiles.git"
    scope: local
    repo: "~/.dotfiles"
  become: true
  become_user: "{{ luizribeiro_username }}"
- name: install dotfiles
  command: "~/.dotfiles/install.sh -A"
  become: true
  become_user: "{{ luizribeiro_username }}"
