- name: restart influxdb
  systemd:
    name: influxdb
    state: restarted
- name: restart grafana
  systemd:
    name: grafana
    state: restarted
- name: restart telegraf
  systemd:
    name: telegraf
    state: restarted
