---
- name: Install cronie
  pacman:
    name: cronie
    state: present
  tags: packages
- name: cronie is enabled and running
  systemd:
    name: cronie
    enabled: yes
    state: started
  tags: systemctl
