---
- name: Install ufw
  pacman:
    name: ufw
    state: present
  tags: packages
- name: ufw daemon is enabled and running
  systemd:
    name: ufw
    enabled: true
    state: started
  tags: systemctl
- name: Deny all traffic by default
  ufw:
    default: deny
  tags: firewall
- name: Include custom firewall rules
  include_tasks: "firewall/{{ item }}.yaml"
  when: ('firewall/' + item + '.yaml') is file
  with_items: "{{ group_names }}"
