---
- include: base.yaml

- name: Install networking tools
  pacman:
    name:
      - iperf
      - nmap
      - speedtest-cli
      - sshfs
      - traceroute
    state: present
  tags: packages
- name: Install man pages
  pacman:
    name:
      - man-db
      - man-pages
    state: present
  tags: packages

- include: users.yaml
- include: ntp.yaml
- include: cron.yaml
- include: pacman.yaml
- include: sshd.yaml
- include: sshguard.yaml
- include: monit.yaml
- include: security.yaml
- include: firewall.yaml
