---
- include: base.yaml

- name: Ensure wheel group exists
  group:
    name: wheel
    state: present
- name: Install networking tools
  package:
    name:
      - iperf
      - nmap
      - speedtest-cli
      - sshfs
      - traceroute
    state: present
  tags: packages
- name: Install man db
  package:
    name:
      - man-db
    state: present
  tags: packages
- name: Install man pages
  package:
    name:
      - man-pages
    state: present
  when: ansible_distribution == 'Archlinux'
  tags: packages

- include: users.yaml
- include: ntp.yaml
- include: firewall.yaml
- include: cron.yaml
  when: ansible_distribution == 'Archlinux'
- include: sshd.yaml
- include: sshguard.yaml
  when: ansible_distribution == 'Archlinux'
- include: security.yaml

- name: Firewall is enabled
  ufw:
    state: enabled
  tags: firewall
