---
- name: Install Monit server
  pacman:
    name: monit
    state: present
  tags: packages
- name: Setup monitrc
  template:
    src: files/etc/monitrc.jinja
    dest: /etc/monitrc
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    validate: "monit -t -c %s"
  notify: restart monit
  tags: configuration
- name: Setup monitrc.d
  copy:
    src: files/etc/monitrc.d/
    dest: /etc/monitrc.d/
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
    # TODO: figure out a way to validate this
  notify: restart monit
  tags: configuration
- name: Create /var/monit directory
  file:
    path: /var/monit
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags: configuration
- name: monit is enabled and running
  systemd:
    name: monit
    enabled: true
    state: started
  tags: systemctl
- name: Setup monit web access on nginx
  when: "'webserver' in ansible_role_names"
  copy:
    src: files/etc/nginx/conf.d/10-host.d/
    dest: /etc/nginx/conf.d/10-host.d/
    owner: http
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  notify: reload nginx
  tags: configuration
