---
- name: Install ntp
  pacman:
    name: ntp
    state: present
  tags: packages
- name: ntpd is enabled and running
  systemd:
    name: ntpd
    enabled: true
    state: started
  tags: systemctl
