---
- name: Install pacman-contrib
  pacman:
    name: pacman-contrib
    state: present
  tags: packages
- name: "Setup aur_builder user"
  user:
    name: aur_builder
    group: wheel
  tags: configuration
- name: "Allow aur_builder to sudo"
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: "visudo -cf %s"
  tags: configuration
- name: "Install yay"
  aur:
    name: yay
    use: makepkg
    skip_installed: true
  become: true
  become_user: aur_builder
  tags: packages
- name: "Install checkupdates+aur"
  aur:
    name: checkupdates+aur
    skip_installed: true
  become: true
  become_user: aur_builder
  tags: packages
- name: Setup hooks directory for pacman
  file:
    path: /etc/pacman.d/hooks
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
- name: Setup script for restarting daemons
  copy:
    src: files/etc/pacman.d/hooks/99-restart-daemons.sh
    dest: /etc/pacman.d/hooks/99-restart-daemons.sh
    owner: root
    group: root
    mode: u=rwx,g=r,o=r
- name: Setup pacman hook for restarting daemons
  copy:
    src: files/etc/pacman.d/hooks/99-restart-daemons.hook
    dest: /etc/pacman.d/hooks/99-restart-daemons.hook
    owner: root
    group: root
    mode: u=rw,g=r,o=r
