---
- name: Install openssh
  pacman:
    name: openssh
    state: present
  tags: packages
- name: Setup sshd_config
  copy:
    src: files/etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    validate: "sshd -tf %s"
  notify: restart sshd
  tags: configuration
- name: Allow (limited) SSH traffic from anywhere
  ufw:
    rule: limit
    port: "22"
  tags: firewall
- name: Allow (limited) mosh traffic from anywhere
  ufw:
    rule: limit
    port: 60001:60999
    protocol: udp
  tags: firewall
- name: sshd is enabled and running
  systemd:
    name: sshd
    enabled: true
    state: started
  tags: systemctl
