---
- name: Install openssh
  pacman:
    name: openssh
    state: present
  tags: packages
- name: Setup sshd_config
  template:
    src: files/etc/ssh/sshd_config.jinja
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    validate: "sshd -tf %s"
  notify: restart sshd
  tags: configuration
- name: Setup pam.d/ssh
  template:
    src: files/etc/pam.d/sshd.jinja
    dest: /etc/pam.d/sshd
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: ssh_require_2fac
  notify: restart sshd
  tags: configuration
- name: Setup /etc/yubikey_mappings
  copy:
    src: files/etc/yubikey_mappings
    dest: /etc/yubikey_mappings
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: ssh_require_2fac
  notify: restart sshd
  tags: configuration
- name: Allow (limited) SSH traffic from anywhere
  ufw:
    rule: limit
    port: "22"
  tags: firewall
- name: Allow (limited) mosh traffic from anywhere
  ufw:
    rule: limit
    port: 60001:60999
    protocol: udp
  tags: firewall
- name: sshd is enabled and running
  systemd:
    name: sshd
    enabled: true
    state: started
  tags: systemctl
