---
- name: Install openssh
  pacman:
    name: openssh
    state: present
  tags: packages
- name: Setup sshd_config
  template:
    src: files/etc/ssh/sshd_config.jinja
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    validate: "sshd -tf %s"
  notify: restart sshd
  tags: configuration
- name: Install openssh
  block:
    - name: Install pam modules for 2fac
      pacman:
        name:
          - libpam-google-authenticator
          - yubico-pam
        state: present
      tags: packages
    - name: Setup pam.d/ssh
      template:
        src: files/etc/pam.d/sshd.jinja
        dest: /etc/pam.d/sshd
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      notify: restart sshd
      tags: configuration
    - name: Setup /etc/yubikey_mappings
      copy:
        src: files/etc/yubikey_mappings
        dest: /etc/yubikey_mappings
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      notify: restart sshd
      tags: configuration
  when: ssh_require_2fac
- name: Allow (limited) SSH traffic from anywhere
  ufw:
    # if running on molecule tests, we just allow. this is because molecule
    # tests end up creating lots of ssh connections and we don't want them to
    # end up being rate limited by the firewall
    rule: "{{ 'limit' if not is_test_environment else 'allow' }}"
    port: "22"
  tags: firewall
- name: Allow (limited) mosh traffic from anywhere
  ufw:
    rule: limit
    port: 60001:60999
    protocol: udp
  tags: firewall
- name: sshd is enabled and running
  systemd:
    name: sshd
    enabled: true
    state: started
  tags: systemctl
