- name: Install sshguard
  pacman:
    name: sshguard
    state: present
  tags: packages
- name: Setup /etc/ufw/before.rules
  template:
    src: files/etc/ufw/before.rules
    dest: /etc/ufw/before.rules
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags: configuration
- name: sshguard is enabled and running
  systemd:
    name: sshguard
    enabled: yes
    state: started
  tags: systemctl
