---
- name: restart pihole-FTL
  systemd:
    name: pihole-FTL
    state: restarted
- name: update pihole gravity
  command: /usr/bin/pihole -g
  become: true
- name: restart php-fpm
  systemd:
    name: php-fpm
    state: restarted
