---
- name: setup yabai
  command: yabai --install-sa
  become: true
  notify: restart Dock.app
- name: restart Dock.app
  command: killall Dock
- name: restart local.clipboard-daemon
  community.general.launchd:
    name: local.clipboard-daemon
    state: restarted
