---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Update pacman cache
      pacman:
        update_cache: true
      when: ansible_distribution == 'Archlinux'
    - name: Update apt cache
      apt:
        update_cache: true
      when: ansible_distribution == 'Debian'
