#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <hosts>"
    exit 1
fi

set -eo pipefail
OLD_DIR="$(pwd)"
cd "$(dirname "$0")/.." || exit 1

source ./scripts/src/common.sh

hosts=($(list_hosts "$1"))
for host in "${hosts[@]}"; do
  user=$(get_user "$host")
  echo "Connecting to $host..."
done
