#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <hosts>"
  exit 1
fi

set -eo pipefail
OLD_DIR="$(pwd)"
cd "$(dirname "$0")/.." || exit 1
source ./scripts/src/common.sh

HOSTS="$1"
if [ "$(num_hosts "$HOSTS")" -eq "0" ]; then
  echo "No hosts in inventory matched \"$HOSTS\""
  cd "$OLD_DIR"
  exit 1
fi

./scripts/initssh "$HOSTS"
ansible-playbook ./scripts/playbooks/stop-ec2-instance.yaml -l "$HOSTS"

cd "$OLD_DIR" || exit 1
