#!/bin/sh

PROJECT_ROOT=$(dirname $(dirname $(realpath $0)))

. $PROJECT_ROOT/scripts/lib/getoptions.sh
. $PROJECT_ROOT/scripts/lib/getoptions_help.sh

parser_definition() {
  setup REST help:usage -- \
    "Usage: ${2##*/} [options] [arguments]"
  param NAME -n --name init:="devvm" -- \
    "name of the virtual machine" \
    "(default: devvm)"
  disp :usage -h --help
}

eval "$(getoptions parser_definition parse "$0")"
parse "$@"

cd "$PROJECT_ROOT/vms/$NAME"
vagrant destroy || exit 1
cd ..
rm -rf "$PROJECT_ROOT/vms/$NAME"
