- name: Install collectd server
  pacman:
    name: collectd
    state: latest
  register: collectd_upgrade
- name: Setup collectd.conf
  copy:
    src: ../files/etc/collectd.conf
    dest: /etc/collectd.conf
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
  register: collectd_conf
- name: Enable collectd
  systemd:
    name: collectd
    enabled: yes
- name: Check and restart collectd
  block:
    - name: Check collectd config
      command: collectd -t
    - name: Restart collectd
      systemd:
        name: collectd
        state: restarted
  when: collectd_conf.changed or collectd_upgrade.changed
