- name: Install collectd server
  pacman:
    name: collectd
    state: present
  notify: restart collectd
- name: Setup collectd.conf
  copy:
    src: files/etc/collectd.conf
    dest: /etc/collectd.conf
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    validate: 'collectd -t -C %s'
  notify: restart collectd
- name: collectd is enabled and running
  systemd:
    name: collectd
    enabled: yes
    state: started
