- name: Install ufw
  pacman:
    name: ufw
    state: present
- name: ufw is enabled and running
  systemd:
    name: ufw
    enabled: yes
    state: started
- name: Deny all traffic by default
  ufw:
    default: deny
- name: Allow all traffic from LAN
  ufw:
    rule: allow
    from: 192.168.1.0/24
