- name: Install essential user packages
  pacman:
    name:
      - fzf
      - htop
      - iperf
      - jq
      - mosh
      - neovim
      - python-pynvim
      - ripgrep
      - speedtest-cli
      - tmux
      - wget
      - zsh
    state: latest

- include: ntp.yaml
- include: firewall.yaml
- include: pacman.yaml
- include: sshd.yaml
- include: sshguard.yaml
- include: collectd.yaml
