- name: Install essential user packages
  pacman:
    name:
      - fzf
      - htop
      - jq
      - mosh
      - neovim
      - python-pynvim
      - ripgrep
      - tmux
      - wget
      - zsh
    state: present
  tags: packages
- name: Install networking tools
  pacman:
    name:
      - iperf
      - nmap
      - speedtest-cli
      - sshfs
      - traceroute
    state: present
  tags: packages
- name: Install man pages
  pacman:
    name:
      - man-db
      - man-pages
    state: present
  tags: packages

- include: ntp.yaml
- include: firewall.yaml
- include: pacman.yaml
- include: sshd.yaml
- include: sshguard.yaml
- include: collectd.yaml
