- name: Install Monit server
  pacman:
    name: monit
    state: present
  tags: packages
- name: Setup monitrc
  template:
    src: files/etc/monitrc
    dest: /etc/monitrc
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    validate: 'monit -t -c %s'
  notify: restart monit
  tags: configuration
- name: Setup monitrc.d
  copy:
    src: files/etc/monitrc.d/
    dest: /etc/monitrc.d/
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
    # TODO: figure out a way to validate this
  notify: restart monit
  tags: configuration
- name: monit is enabled and running
  systemd:
    name: monit
    enabled: yes
    state: started
  tags: systemctl
