- name: Install pacman-contrib
  pacman:
    name: pacman-contrib
    state: latest
- name: 'Setup aur_builder user'
  user:
    name: aur_builder
    group: wheel
- name: 'Allow aur_builder to sudo'
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
- name: 'Install yay'
  aur:
    name: yay
    use: makepkg
    skip_installed: true
  become: yes
  become_user: aur_builder
