- name: Install openssh
  pacman:
    name: openssh
    state: present
  register: openssh_upgrade
- name: Setup sshd_config
  copy:
    src: files/etc/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
  register: sshd_config
- name: Allow (limited) SSH traffic from anywhere
  ufw:
    rule: limit
    port: '22'
- name: Allow mosh traffic from anywhere
  ufw:
    rule: allow
    port: 60000:60999
    protocol: udp
- name: Enable sshd
  systemd:
    name: sshd
    enabled: yes
- name: Check and restart sshd
  block:
    - name: Check sshd_config
      command: sshd -t
    - name: Restart sshd
      systemd:
        name: sshd
        state: restarted
  when: openssh_upgrade.changed or sshd_config.changed
