---
- name: Install Docker
  pacman:
    name:
      - docker
      - docker-compose
      - python-docker
    state: present
- name: Docker is enabled and running
  systemd:
    name: docker
    enabled: true
    state: started
- name: Setup Docker monit config
  when: "'monit' in ansible_role_names"
  template:
    src: files/etc/monitrc.d/docker.conf
    dest: /etc/monitrc.d/docker.conf
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
  notify: restart monit
