---
version: "3"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /var/lib/hass:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/zigbee:/dev/zigbee
      - /dev/zwave:/dev/zwave
    restart: unless-stopped
    privileged: true
    network_mode: host
