---
- name: Setup apt pinning
  copy:
    src: files/etc/apt/preferences.d/pinning.pref
    dest: /etc/apt/preferences.d/pinning.pref
    owner: root
    group: root
    mode: u=rw,g=r,o=r
- name: Add luizribeiro's GPG key to apt keys
  apt_key:
    url: gpg.l9o.dev
    state: present
- name: Setup Debian apt repositories
  apt_repository:
    repo: >-
      deb {{
        'http://raspbian.raspberrypi.org/raspbian/'
        if ansible_lsb.id == 'Raspbian'
        else 'http://deb.debian.org/debian'
      }}
      {{ repo }} main contrib non-free rpi
    state: present
  with_items:
    - buster
    - bullseye
  loop_control:
    loop_var: repo
  notify: apt update
- name: Install snapd
  apt:
    name: snapd
    state: present
  tags: packages
