- name: Setup static configuration files
  copy:
    src: files/
    dest: /etc/config/
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx
- name: Setup wireless
  template:
    src: templates/wireless
    dest: /etc/config/wireless
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx
- name: Setup ddns
  template:
    src: templates/ddns
    dest: /etc/config/ddns
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx
