# vim: set ft=ruby:

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine313"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
    ansible.config_file = "../../ansible.cfg"
  end
end
