- name: Install fail2ban
  pacman:
    name: fail2ban
    state: present
  tags: packages
- name: Setup fail2ban filter.d
  copy:
    src: files/etc/fail2ban/filter.d/
    dest: /etc/fail2ban/filter.d/
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
  notify: reload fail2ban
  tags: configuration
- name: Setup fail2ban jail.d
  copy:
    src: files/etc/fail2ban/jail.d/
    dest: /etc/fail2ban/jail.d/
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
  notify: reload fail2ban
  tags: configuration
- name: Setup fail2ban jail.local
  copy:
    src: files/etc/fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
  notify: reload fail2ban
  tags: configuration
- name: fail2ban is enabled and running
  systemd:
    name: fail2ban
    enabled: yes
    state: started
  tags: systemctl
