- name: Install goaccess server
  pacman:
    name: goaccess
    state: present
  notify: restart goaccess
- name: Setup goaccess.conf
  copy:
    src: files/etc/goaccess/goaccess.conf
    dest: /etc/goaccess/goaccess.conf
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
  notify: restart goaccess
- name: Setup goaccess.service
  copy:
    src: files/etc/systemd/system/goaccess.service
    dest: /etc/systemd/system/goaccess.service
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
  notify:
    - reload goaccess.service
    - restart goaccess
- name: goaccess is enabled and running
  systemd:
    name: goaccess
    enabled: yes
    state: started
