- include: nginx.yaml
- include: fail2ban.yaml
- include: goaccess.yaml

- name: Setup monit config
  template:
    src: templates/etc/monitrc.d/webserver.conf.jinja
    dest: /etc/monitrc.d/webserver.conf
    owner: root
    group: root
    mode: u+rw,g-rwx,o-rwx
  notify: restart monit
  tags: configuration
