- name: Install nginx
  pacman:
    name: nginx
    # TODO: install apache-tools and setup htpasswd for host
    state: present
  register: nginx_upgrade
- name: Install certbot
  pacman:
    name:
      - certbot-nginx
      - certbot-systemd
    state: present
- name: Setup nginx.conf
  copy:
    src: files/etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: http
    mode: u+rw,g-rwx,o-rwx
  register: nginx_conf
- name: Setup nginx/conf.d
  copy:
    src: files/etc/nginx/conf.d/
    dest: /etc/nginx/conf.d/
    owner: http
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  register: nginx_confd
- name: Setup /srv/http
  copy:
    src: files/srv/http/
    dest: /srv/http/
    owner: http
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
# TODO: setup SSL certs wih certbot and enable certbot.timer
- name: Allow HTTP traffic from anywhere
  ufw:
    rule: allow
    port: '80'
- name: Allow HTTPS traffic from anywhere
  ufw:
    rule: allow
    port: '443'
- name: Enable nginx
  systemd:
    name: nginx
    enabled: yes
- name: Check and restart nginx
  block:
    - name: Check nginx config
      command: nginx -t
    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
  when: nginx_upgrade.changed or nginx_conf.changed or nginx_confd.changed
