- name: Install nginx
  pacman:
    name: nginx
    # TODO: install apache-tools and setup htpasswd for host
    state: present
  notify: restart nginx
- name: Install certbot
  pacman:
    name:
      - certbot-nginx
      - certbot-systemd
    state: present
- name: Setup nginx.conf
  copy:
    src: files/etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: http
    mode: u+rw,g-rwx,o-rwx
    validate: 'nginx -t -c %s'
  notify: restart nginx
- name: Setup nginx/conf.d
  copy:
    src: files/etc/nginx/conf.d/
    dest: /etc/nginx/conf.d/
    owner: http
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
    # TODO: find a way to validate nginx/conf.d
  notify: restart nginx
- name: Setup /srv/http
  copy:
    src: files/srv/http/
    dest: /srv/http/
    owner: http
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
# TODO: setup SSL certs wih certbot and enable certbot.timer
- name: Allow HTTP traffic from anywhere
  ufw:
    rule: allow
    port: '80'
- name: Allow HTTPS traffic from anywhere
  ufw:
    rule: allow
    port: '443'
- name: nginx is enabled and running
  systemd:
    name: nginx
    enabled: yes
    state: started
