backup_paths:
  - /home
backup_excludes:
restic_backup_repo_prefix: "s3:https://{{ secret_wasabi_endpoint }}/{{ secret_wasabi_bucket }}"
restic_backup_repo: "{{ restic_backup_repo_prefix }}/{{ inventory_hostname }}"
backup_user: root
backup_user_group: root
backup_script_path: /root/backup.sh
backup_cron_file: backups
