- name: Install tools for ansible
  pacman:
    name:
      - ansible
      - ansible-lint
    state: present
  when: dev_ansible_tools
  tags: packages
- name: Uninstall python-passlib
  pacman:
    name:
      - python-passlib
    state: absent
  when: dev_ansible_tools
  tags: packages
