---
- name: Install basic development tools
  package:
    name:
      - git
      - shellcheck
      - yamllint
    state: present
  tags: packages

- name: Install python3-pip
  package:
    name: python3-pip
    state: present
  when: dev_python_tools
  tags: packages
- name: Install python3-venv
  package:
    name: python3-venv
    state: present
  when: dev_python_tools
  tags: packages

- name: Install tools for Python development
  pip:
    name:
      - black
      - poetry
    executable: pip3
  when: dev_python_tools
  tags: packages
