---
- name: Install basic development tools
  homebrew:
    name:
      - git
      - shellcheck
    state: present
  tags: packages

- name: Check if watchman is installed
  shell: command -v watchman >/dev/null 2>&1
  register: is_watchman_installed
  ignore_errors: true
  changed_when: false
  tags: packages
- name: Install watchman
  homebrew:
    name:
      - watchman
  when: not is_watchman_installed
  tags: packages

- name: Install tools for ansible
  homebrew:
    name:
      - ansible
      - ansible-lint
      - molecule
      - pipenv
      - prettier
      - rsync
      - yamllint
    state: present
  when: dev_ansible_tools
  tags: packages

- name: Install tools for working with VMs
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - vagrant
    - virtualbox
    - virtualbox-extension-pack
  when: dev_vm_tools
  tags: packages

- name: Install tools for AWS
  homebrew:
    name:
      - awscli
      - aws-shell
    state: present
  when: dev_aws_tools
  tags: packages

- name: Install tools for qmk_firmware
  block:
    - name: Tap osx-cross
      homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items:
        - osx-cross/arm
        - osx-cross/avr
    - name: Make /usr/local/bin owned by myself
      file:
        path: /usr/local/bin
        state: directory
        owner: "{{ ansible_user }}"
      become: true
    - name: Install avr/arm compilers for qmk_firmware
      homebrew:
        name:
          - arm-gcc-bin
          - avr-gcc
        state: installed
    - name: Link arm-gcc for qmk_firmware
      command: brew link --force arm-gcc-bin@
      args:
        creates: /usr/local/bin/arm-none-eabi-gcc
    - name: Link avr-gcc for qmk_firmware
      command: brew link --force avr-gcc@
      args:
        creates: /usr/local/bin/avr-gcc
    - name: Install qmk_firmware flashing tools
      homebrew:
        name:
          - avrdude
          - dfu-programmer
          - dfu-util
        state: present
  when: dev_qmk_firmware_tools
  tags: packages

- name: Install tools for C/C++ development
  homebrew:
    name:
      - automake
      - clang-format
      - llvm
      - pkg-config
    state: present
  when: dev_cpp_tools
  tags: packages

- name: Install tools for Python development
  homebrew:
    name:
      - black
      - pipenv
    state: present
  when: dev_python_tools
  tags: packages
