- name: Install tools for ansible
  homebrew:
    name:
      - ansible
      - ansible-lint
    state: present
  when: dev_ansible_tools
  tags: packages
- name: Uninstall passlib
  pip:
    name:
      - passlib
    state: absent
  when: dev_ansible_tools
  tags: packages
