- name: Install tools for ansible
  homebrew:
    name:
      - ansible
      - ansible-lint
      - molecule
      - prettier
      - yamllint
    state: present
  when: dev_ansible_tools
  tags: packages
