---
- name: Install Karabiner-Elements
  homebrew_cask:
    name: karabiner-elements
    state: present
- name: Detect Touch ID support
  shell: pgrep ControlStrip
  ignore_errors: true
  register: touch_id_result
- name: Enable Touch ID for sudo commands
  lineinfile:
    path: /etc/pam.d/sudo
    line: "auth       sufficient     pam_tid.so"
    insertbefore: "^auth       sufficient     pam_smartcard.so$"
  become: true
  when: touch_id_result.rc == 0 and touch_id_result.stdout != ''
