- name: Install OSX tools
  homebrew:
    name:
      - coreutils
      - gpg
      - mas
      - pinentry-mac
    state: present
  tags: packages
- name: Refresh sudo cache
  command: "echo none"
  become: yes
- name: Install Homebrew Casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - alfred
    - dropbox
    - gpg-suite
    - istat-menus
    - iterm2
    - monitorcontrol
    - spotify
  tags: packages
- name: Install Additional Homebrew Casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ osx_additional_casks }}"
  when: osx_additional_casks != None and (osx_additional_casks | length) > 0
  tags: packages
- name: Tap homebrew/cask-fonts
  homebrew_tap:
    name: homebrew/cask-fonts
    state: present
  tags: packages
- name: Install Hack Nerd Font
  homebrew_cask:
    name: font-hack-nerd-font
    state: present
  tags: packages
- name: Check installed MAS apps
  command: mas list
  register: mas_list
  check_mode: false
  changed_when: false
- name: Install MAS apps
  command: mas install "{{ item.id|default(item) }}"
  with_items:
    - { id: 585829637, name: "Todoist" }
  when: (item.id | string) not in mas_list.stdout
- name: Install additional MAS apps
  command: mas install "{{ item.id|default(item) }}"
  with_items: "{{ osx_additional_mas_apps }}"
  when: >
    osx_additional_mas_apps != None and (osx_additional_mas_apps | length) > 0
    and (item.id | string) not in mas_list.stdout
