---
- name: Install OSX tools
  homebrew:
    name:
      - coreutils
      - gpg
      - mas
      - pinentry-mac
      - terminal-notifier
    state: present
  tags: packages
- name: Install Homebrew Casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - alfred
    - authy
    - dash
    - dropbox
    - gpg-suite
    - intel-power-gadget
    - istat-menus
    - iterm2
    - lastpass
    - monitorcontrol
    - spotify
  tags: packages
- name: Install Additional Homebrew Casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ osx_additional_casks }}"
  when: osx_additional_casks != None and (osx_additional_casks | length) > 0
  tags: packages
- name: Tap homebrew/cask-fonts
  homebrew_tap:
    name: homebrew/cask-fonts
    state: present
  tags: packages
- name: Install Hack Nerd Font
  homebrew_cask:
    name: font-hack-nerd-font
    state: present
  tags: packages
- name: Check installed MAS apps
  command: mas list
  register: mas_list
  check_mode: false
  changed_when: false
- name: Install MAS apps
  command: mas install "{{ item.id|default(item) }}"
  with_items:
    - { id: 585829637, name: "Todoist" }
  register: mas_install
  changed_when: "'is already installed' not in mas_install.stdout"
- name: Install additional MAS apps
  command: mas install "{{ item.id|default(item) }}"
  with_items: "{{ osx_additional_mas_apps }}"
  when: >-
    osx_additional_mas_apps != None
    and (osx_additional_mas_apps | length) > 0
  register: mas_install
  changed_when: "'is already installed' not in mas_install.stdout"
- include: macbook.yaml
  when: ansible_model is match("MacBook.*")
- include: yabai.yaml
- include: brew-update-notifier.yaml
- include: clipboard-daemon.yaml
