- name: Tap koekeishiya/formulae
  homebrew_tap:
    name: koekeishiya/formulae
    state: present
  tags: packages
- name: Install yabai and skhd
  homebrew:
    name:
      - yabai
      - skhd
    state: present
  tags: packages
  notify: setup yabai
- name: yabai is enabled and running
  homebrew_services:
    name: "{{ item }}"
    state: started
  with_items:
    - yabai
    - skhd
  tags: systemctl
