- hosts: nuc
  become: yes
  tasks:
    - name: Install essential user packages
      pacman:
        name:
          - fzf
          - htop
          - iperf
          - jq
          - mosh
          - neovim
          - ripgrep
          - speedtest-cli
          - tmux
          - wget
          - zsh
    - name: Install essential server packages
      pacman:
        name:
          - ntp
    - name: Enable and start ntpd
      systemd:
        name: ntpd
        enabled: yes
        state: started
