- hosts: nuc
  become: yes
  tasks:
    - name: Install goaccess server
      pacman:
        name: goaccess
        state: latest
        update_cache: yes
      register: upgrade
    - name: Setup goaccess.conf
      copy:
        src: ../etc/goaccess/goaccess.conf
        dest: /etc/goaccess/goaccess.conf
        owner: root
        group: root
        mode: u+rw,g-rwx,o-rwx
      register: conf
    - name: Setup goaccess.service
      copy:
        src: ../etc/systemd/system/goaccess.service
        dest: /etc/systemd/system/goaccess.service
        owner: root
        group: root
        mode: u+rw,g-rwx,o-rwx
      register: service
    - name: Reload goaccess.service
      systemd:
        daemon_reload: yes
    - name: Enable goaccess
      systemd:
        name: goaccess
        enabled: yes
      when: service.changed
    - name: Restart goaccess
      systemd:
        name: goaccess
        state: restarted
      when: conf.changed or service.changed or upgrade.changed
