#!/usr/bin/env ansible-playbook --ask-become-pass
---
- hosts: macbook
  vars_files:
    - "{{ inventory_dir }}/secrets.yaml"
  pre_tasks:
    - name: Check we are running on the right host
      assert:
        that:
          - ansible_distribution == 'MacOSX'
          - ansible_user == 'luizribeiro'
        quiet: true
    - name: Refresh sudo cache
      command: "echo none"
      become: true
      check_mode: false
      changed_when: false
  roles:
    - role: luizribeiro
      vars:
        luizribeiro_username: luizribeiro
        luizribeiro_primary_group: "{{ omit }}"
        luizribeiro_groups:
          - admin
      tags: luizribeiro
    - role: dev
      vars:
        dev_ansible_tools: true
      tags: dev
    - role: osx
      vars:
        osx_additional_casks:
          - limechat
          - quip
          - slack
      tags: osx
