#!/usr/bin/env ansible-playbook
---
- hosts: openwrt
  vars_files:
    - "{{ inventory_dir }}/secrets.yaml"
  roles:
    - role: openwrt
    - role: backup
      vars:
        backup_paths:
          - /
        backup_excludes:
          - /proc
          - /sys
          - /tmp
          - /var
