---
- include: packages.yaml
  tags: packages
- include: luci-mqtt-patch.yaml
  tags: packages
- include: config.yaml
  tags: configuration
- include: utils.yaml
  tags: packages
- include: services.yaml
  tags: systemctl
