---
- name: Install necessary packages for Ansible
  opkg:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-light
    - python3-logging
    - python3-multiprocessing
    - python3-distutils
    - rsync
    - shadow-usermod
    - patch
- name: Install collectd
  opkg:
    name: "{{ item }}"
    state: present
  with_items:
    - collectd
    - collectd-mod-cpu
    - collectd-mod-df
    - collectd-mod-disk
    - collectd-mod-interface
    - collectd-mod-iwinfo
    - collectd-mod-load
    - collectd-mod-memory
    - collectd-mod-mqtt
    - collectd-mod-rrdtool
    - collectd-mod-uptime
- name: Install utilities
  opkg:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - iperf
    - openssh-sftp-server
- name: Install luci plugins
  opkg:
    name: "{{ item }}"
    state: present
  with_items:
    - luci-app-ddns
    - luci-app-firewall
    - luci-mod-admin-full
    - luci-theme-material
- name: Install base packages
  opkg:
    name: "{{ item }}"
    state: present
  with_items:
    # these are necessary for the backup scripts
    - bash
    - ca-certificates
    - coreutils-timeout
