- name: Install necessary packages for Ansible
  opkg:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-light
    - python3-logging
    - python3-multiprocessing
    - python3-distutils
    - rsync
