- name: 'Create {{ username }} user account'
  user:
    name: "{{ username }}"
    password: "{{ secret_luizribeiro_initial_password | password_hash('sha512') }}"
    update_password: on_create
    shell: /bin/zsh
    group: users
    groups: wheel,sshusers
    append: yes
    expires: -1
  tags: configuration
- name: 'Setup SSH Authorized Keys for {{ username }}'
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ secret_luizribeiro_ssh_authorized_keys }}"
  tags: configuration
- name: 'Setup dotfiles'
  become: yes
  become_user: "{{ username }}"
  block:
    - name: 'Clone dotfiles git repo'
      git:
        repo: 'https://github.com/luizribeiro/dotfiles'
        dest: '~/.dotfiles'
      register: dotfiles
    - name: 'Setup github remote for pushing changes'
      git_config:
        name: 'remote.github.url'
        value: 'git@github.com:luizribeiro/dotfiles.git'
        scope: local
        repo: '~/.dotfiles'
    - name: 'Install dotfiles'
      command: '~/.dotfiles/install.sh -A'
      when: dotfiles.changed
  tags: configuration
