- name: 'Create {{ luizribeiro_username }} user account'
  user:
    name: "{{ luizribeiro_username }}"
    password: "{{ secret_luizribeiro_initial_password | password_hash('sha512') }}"
    update_password: on_create
    shell: /bin/zsh
    group: "{{ luizribeiro_primary_group }}"
    groups: "{{ luizribeiro_groups | join(',') }}"
    append: yes
    expires: -1
  tags: configuration
- name: 'Setup SSH Authorized Keys for {{ luizribeiro_username }}'
  authorized_key:
    user: "{{ luizribeiro_username }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ secret_luizribeiro_ssh_authorized_keys }}"
  loop_control:
    label: "{{ item.split(' ')[-1] }}"
  tags: configuration
- name: 'Setup dotfiles'
  become: yes
  become_user: "{{ luizribeiro_username }}"
  block:
    - name: 'Clone dotfiles git repo'
      git:
        repo: 'https://github.com/luizribeiro/dotfiles'
        dest: '~/.dotfiles'
        version: 'HEAD'
      notify: install dotfiles
    - name: 'Setup github remote for pushing changes'
      git_config:
        name: 'remote.github.url'
        value: 'git@github.com:luizribeiro/dotfiles.git'
        scope: local
        repo: '~/.dotfiles'
  tags: configuration

- include: packages.yaml
