---
- name: "Create {{ luizribeiro_username }} user account"
  user:
    name: "{{ luizribeiro_username }}"
    password: >-
      {{ secret_luizribeiro_initial_password | password_hash('sha512') }}
    update_password: on_create
    shell: /bin/zsh
    group: "{{ luizribeiro_primary_group }}"
    # TODO: split this between groups and additional groups
    groups: "{{ luizribeiro_groups | join(',') }}"
    append: true
    expires: -1
  tags: configuration
- name: "Setup SSH Authorized Keys for {{ luizribeiro_username }}"
  authorized_key:
    user: "{{ luizribeiro_username }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ secret_luizribeiro_ssh_authorized_keys }}"
  loop_control:
    label: "{{ item.split(' ')[-1] }}"
  tags: configuration
- name: "Setup Google Authenticator"
  copy:
    dest: "~/.google_authenticator"
    content: "{{ secret_google_authenticator }}\n\" TOTP_AUTH\n"
    mode: u=r,g-rwx,o-rwx
  become: true
  become_user: "{{ luizribeiro_username }}"
  when: luizribeiro_setup_google_authenticator
- name: Check if ~/.dotfiles exists
  stat:
    path: "~/.dotfiles"
  become: true
  become_user: "{{ luizribeiro_username }}"
  register: dotfiles
  changed_when: not dotfiles.stat.exists
  notify: clone dotfiles repo
- name: Check if ~/.local/bin exists
  file:
    path: ~/.local/bin
    state: directory

- include: packages.yaml
