- name: 'Create {{ username }} user account'
  user:
    name: "{{ username }}"
    password: "{{ secret_luizribeiro_initial_password | password_hash('sha512') }}"
    update_password: on_create
    shell: /bin/zsh
    group: users
    groups: wheel,sshusers
    append: yes
    expires: -1
  tags: configuration
- name: 'Setup SSH Authorized Keys for {{ username }}'
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ secret_luizribeiro_ssh_authorized_keys }}"
  tags: configuration
