---
- name: Install neovim
  homebrew:
    name:
      - neovim
    state: present
  tags: packages
- name: Install pynvim
  pip:
    name:
      - pynvim
    state: present
    executable: pip3.8
  tags: packages
