---
- name: Install essential user packages
  package:
    name:
      - fzf
      - htop
      - jq
      - mosh
      - ncdu
      - ripgrep
      - tldr
      - tmux
      - wget
      - zsh
      - "{{ 'netcat' if ansible_distribution == 'MacOSX' else 'nmap-netcat' }}"
    state: present
  tags: packages

- name: Setup neovim
  include: "neovim-{{ ansible_distribution | lower }}.yaml"
