---
- name: Install essential user packages
  package:
    name:
      - fzf
      - htop
      - jq
      - mosh
      - ncdu
      - nmap
      - ripgrep
      - rsync
      - tldr
      - tmux
      - wget
      - zsh
    state: present
  tags: packages

- name: Setup neovim
  include_tasks: "neovim-{{ ansible_distribution | lower }}.yaml"
