---
- name: Install essential user packages
  package:
    name:
      - fzf
      - htop
      - jq
      - mosh
      - ncdu
      - nmap
      - ripgrep
      - rsync
      - tmux
      - wget
      - zsh
    state: present
  tags: packages
- name: Install not as essential user packages
  package:
    name:
      - tldr
    state: present
  tags: packages
  when: ansible_distribution != 'Alpine'

- name: Install email software
  package:
    name:
      - mutt
      - w3m
    state: present
  tags: packages
  when: ansible_distribution == 'MacOSX'

- name: Setup neovim
  include_tasks: "neovim-{{ ansible_distribution | lower }}.yaml"
