---
name: Build VMs and upload to cloud

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  setup-venv:
    # vagrant and virtualization is only available on macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: syphar/restore-virtualenv@v1.1
        id: venv-cache

      - uses: abatilo/actions-poetry@v2.1.1
        if: steps.setup-venv.outputs.cache-hit != 'true'
      - name: Install Python dependencies
        run: poetry install -vv
        if: steps.setup-venv.outputs.cache-hit != 'true'

  build:
    runs-on: macos-latest
    needs: setup-venv
    strategy:
      max-parallel: 4
      matrix:
        vm: [arch-base, debian10-base, alpine-base]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: syphar/restore-virtualenv@v1.1
        id: venv-cache

      - name: Setup Vagrant Cloud token
        env:
          VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
        run: vagrant cloud auth login --token "$VAGRANT_CLOUD_TOKEN"

      - name: Build and upload VM to Vagrant Cloud
        run: |
          cd boxes/
          ./build.sh ${{ matrix.vm }}
