---
name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        role-to-test: [pihole, server]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: abatilo/actions-poetry@v2.1.0

      - name: Install Python dependencies
        run: poetry install -vv
      - name: Install Ansible Galaxy requirements
        run: poetry run ansible-galaxy install -r requirements.yml

      - name: Run Ansible Lint against playbooks
        run: poetry run ansible-lint
      - name: Run YAML Lint
        run: poetry run yamllint .

      - name: Run Python static analysis checks
        run: poetry run pyre --noninteractive

      - name: Run molecule tests
        run: |
          cd ${{ matrix.role-to-test }}
          poetry run molecule test
