- name: Install pi-hole-server
  become_user: aur_builder
  aur:
    name: pi-hole-server
  register: pihole_upgrade
- name: Setup pi-hole-server configuration
  copy:
    src: ../files/etc/pihole/
    dest: /etc/pihole/
    owner: pihole
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  register: pihole_config
- name: Setup dnsmasq configuration
  copy:
    src: ../files/etc/dnsmasq.d/
    dest: /etc/dnsmasq.d/
    owner: pihole
    mode: u+rw,g-rwx,o-rwx
    directory_mode: u+rwx,g-rwx,o-rwx
  register: dnsmasq_config
- name: Allow DNS queries from IoT
  ufw:
    rule: allow
    from: 192.168.2.0/24
    port: '53'
    protocol: udp
- name: Enable pihole-FTL
  systemd:
    name: pihole-FTL
    enabled: yes
- name: Restart pihole-FTL
  systemd:
    name: pihole-FTL
    state: restarted
  when: pihole_upgrade.changed or pihole_config.changed or dnsmasq_config.changed

 # Setup PHP
- name: Install PHP
  pacman:
    name:
      - php
      - php-sqlite
    state: latest
    update_cache: yes
- name: Enable PHP extensions
  lineinfile:
    dest: /etc/php/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: 'extension=pdo_sqlite', line: 'extension=pdo_sqlite' }
    - { regexp: 'extension=sqlite3', line: 'extension=sqlite3' }
    - { regexp: 'extension=sockets', line: 'extension=sockets' }

- name: Install PHP FastCGI Process Manager (FPM)
  pacman:
    name:
      - php-fpm
    state: latest
    update_cache: yes
  register: php_fpm_upgrade
- name: Enable sockets PHP extension
  lineinfile:
    dest: /etc/php/php-fpm.d/www.conf
    regexp: 'listen ='
    line: 'listen = /var/run/php-fpm/fpm-www.sock'
  register: php_fpm_config
- name: Enable php-fpm
  systemd:
    name: php-fpm
    enabled: yes
- name: Restart php-fpm
  systemd:
    name: php-fpm
    state: restarted
  when: php_fpm_upgrade.changed or php_fpm_config.changed
